services:
  app_proxy:
    environment:
      APP_HOST: hammy-bch-solo-node_app_1
      APP_PORT: 3000
      JWT_SECRET: "${JWT_SECRET}"
    networks:
      - umbrel_main_network

  bchn:
    build:
      context: ./services/bchn
    user: "1000:1000"
    restart: unless-stopped
    stop_grace_period: 15m30s
    ports:
      - "28333:28333/tcp"
    volumes:
      - ${APP_DATA_DIR}/data/node:/data
      - ./data/templates:/templates:ro
    environment:
      APPS_SUBNET: "${NETWORK_IP}/16"
      RPC_USER: "bch"
      RPC_PASSWORD: "${APP_PASSWORD}"
      BCH_P2P_PORT: "28333"
      BCH_RPC_PORT: "28332"
      BCH_ZMQ_HASHBLOCK_PORT: "28334"
    healthcheck:
      test: ["CMD-SHELL", "bitcoin-cli -datadir=/data getblockchaininfo >/dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 2m

  ckpool:
    build:
      context: ./services/ckpool
    user: "1000:1000"
    depends_on:
      - bchn
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "4633:3333/tcp"
    volumes:
      - ${APP_DATA_DIR}/data/pool/config:/config
      - ${APP_DATA_DIR}/data/pool/www:/www
      - ./data/templates:/templates:ro
    environment:
      RPC_USER: "bch"
      RPC_PASSWORD: "${APP_PASSWORD}"
      BCH_RPC_PORT: "28332"
      BCH_ZMQ_HASHBLOCK_PORT: "28334"
      PAYOUT_ADDRESS: "CHANGEME_BCH_PAYOUT_ADDRESS"

  app:
    build:
      context: ./web
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 30s
    depends_on:
      - bchn
      - ckpool
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      NETWORK_IP: "${NETWORK_IP}"
      BCH_RPC_HOST: "bchn"
      BCH_RPC_PORT: "28332"
      BCH_RPC_USER: "bch"
      BCH_RPC_PASS: "${APP_PASSWORD}"
      CKPOOL_STATUS_DIR: "/data/pool/www/pool"
      CKPOOL_USERS_DIR: "/data/pool/www/users"
      CKPOOL_LOG_PATH: "/data/pool/www/ckpool.log"
      CKPOOL_SHARELOG_ROOT: "/data/pool/www"
      CKPOOL_CONF_PATH: "/data/pool/config/ckpool.conf"
      APP_CHANNEL: "BETA"
      APP_VERSION_SUFFIX: ""
      BCHN_IMAGE: "local/bch-solo-node-bchn"
      CKPOOL_IMAGE: "local/bch-solo-node-ckpool"
      STATIC_DIR: "/app/static"
      SUPPORT_CHECKIN_URL: ""
      SUPPORT_TICKET_URL: ""

networks:
  umbrel_main_network:
    external: true
    name: umbrel_main_network
